version: '3.7'

services:
  database:
    image: postgres
    container_name: customerxchallenge_db
    restart: always
    environment:
      - POSTGRES_USER=user_augusto
      - POSTGRES_PASSWORD=augusto_pw
      - POSTGRES_DB=customerxchallenge
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: customerxchallenge
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
